version: "3.9"
services:
  miapp:
    build: .
    ports:
      - "3000:3000"
    links:
      - baseDatos  
  baseDatos:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'DBImportadoraPrueba'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    expose:
      - '3306'
